# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: berry456

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: berry456
    salt: "FO@NOcwICc0"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  example.com:
    env:
      db_password: berry456
      # Generate your keys here: https://roots.io/salts.html
      auth_key: ".6<`.pn28+BwA5+X}GQ9:9cHg/[:`?R;^FO@NOcwICc0.flYaCwqRR;{IuMPB{yo"
      secure_auth_key: "f4C`iY/stci:<rP2eI2G)tFB(<UMxH(t)S-60j!uKUwgq)2!GXb`jmDr}-19!PEp"
      logged_in_key: "H.%+6e}qRJb)E^:O>C@s>-o1oLS{v)ggv1Th.v]k^&pdW!sOgot0`Xlj|@/e}1&T"
      nonce_key: "WBEt@o^9KWhGa^qObpeH()%Eqr*efa.J&m7X1TlLis6B$`Bo,{w<Ktb4;A}qrCq."
      auth_salt: "uwFC82)>QIw!&Q.nZ<6<Ihc{nQ^D`BQ/O*C2aLJdkN=&r?8pSp/b26hA8-}<=jm."
      secure_auth_salt: "w@!9[omKW+e7N-.v.4+sr^upEl%RxIfnl:0feJ(X,4ZHqw-8-ZK(xtNc!fKwVcz?"
      logged_in_salt: "5%bH5j<1<P[Qe?s4{sc9w4nHtafT76S$nb@f_$jAr|Mt5Cu2Q2bg;6b2!.hW,@=B"
      nonce_salt: "lKX|IQ!sskJ82Lvo8/3gSSE[Lm}4H@fgI&%Z3<3HQ*=jdN}rc#S5A>_@^|P436Dd"
